"""Docker-to-WireGuard routing rules (guide §17) and host firewall openings (guide §4).

The guide's `iptables -A` commands are not idempotent and do not survive a reboot. Rather
than reach for iptables-persistent — which fights with Docker over the same tables — edgekit
writes a small idempotent script and a systemd unit that replays it after docker.service and
wg-quick@wg0 are up. Each rule is added only if an identical rule is absent (`iptables -C`),
so running the script any number of times converges on the same ruleset.
"""

from __future__ import annotations

import logging
import re
import stat
from dataclasses import dataclass
from pathlib import Path

from ..config import Config
from ..paths import FIREWALL_SCRIPT, FIREWALL_UNIT
from .shell import has, run, systemctl

log = logging.getLogger("edgekit.firewall")

SCRIPT_TEMPLATE = """#!/bin/sh
# Managed by edgekit. Regenerated by `edgekit provision`; edits are not preserved.
#
# Bridges the Docker bridge network to the WireGuard tunnel so that containers
# (Nginx Proxy Manager) can reach peers such as {wg_subnet}.
set -eu

DOCKER_IF="{docker_if}"
DOCKER_SUBNET="{docker_subnet}"
WG_IF="{wg_if}"
WG_SUBNET="{wg_subnet}"

# add <table> <chain> <rule...> — appends only when no identical rule exists.
add() {{
    table="$1"; shift
    chain="$1"; shift
    if ! iptables -t "$table" -C "$chain" "$@" 2>/dev/null; then
        iptables -t "$table" -A "$chain" "$@"
    fi
}}

# Container -> peer.
add filter FORWARD -i "$DOCKER_IF" -o "$WG_IF" -d "$WG_SUBNET" -j ACCEPT

# Peer -> container, replies only.
add filter FORWARD -i "$WG_IF" -o "$DOCKER_IF" -s "$WG_SUBNET" \\
    -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Peers see traffic as coming from the hub's tunnel address, so they need no route
# back to the Docker subnet.
add nat POSTROUTING -s "$DOCKER_SUBNET" -d "$WG_SUBNET" -o "$WG_IF" -j MASQUERADE
"""

UNIT_TEMPLATE = """[Unit]
Description=edgekit Docker-to-WireGuard forwarding rules
After=network-online.target docker.service wg-quick@{wg_if}.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={script}

[Install]
WantedBy=multi-user.target
"""


def detect_docker_bridge_subnet(default: str = "172.17.0.0/16") -> str:
    """Read the real bridge subnet instead of assuming 172.17.0.0/16 (guide §21)."""
    result = run(
        [
            "docker",
            "network",
            "inspect",
            "bridge",
            "--format",
            "{{(index .IPAM.Config 0).Subnet}}",
        ]
    )
    subnet = result.stdout.strip()
    if result.ok and "/" in subnet:
        return subnet
    log.warning("could not detect the Docker bridge subnet; falling back to %s", default)
    return default


def detect_docker_bridge_interface(default: str = "docker0") -> str:
    """Resolve the bridge's kernel interface name, which is configurable via daemon.json."""
    result = run(
        [
            "docker",
            "network",
            "inspect",
            "bridge",
            "--format",
            '{{index .Options "com.docker.network.bridge.name"}}',
        ]
    )
    name = result.stdout.strip()
    if result.ok and name and name != "<no value>":
        return name
    return default


def write_rules(
    *, docker_subnet: str, wg_subnet: str, wg_if: str, docker_if: str = "docker0"
) -> None:
    """Render the rules script and its boot-time unit."""
    script = SCRIPT_TEMPLATE.format(
        docker_if=docker_if,
        docker_subnet=docker_subnet,
        wg_if=wg_if,
        wg_subnet=wg_subnet,
    )
    FIREWALL_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    FIREWALL_SCRIPT.write_text(script)
    FIREWALL_SCRIPT.chmod(
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
    )

    unit = UNIT_TEMPLATE.format(wg_if=wg_if, script=FIREWALL_SCRIPT)
    if not FIREWALL_UNIT.exists() or FIREWALL_UNIT.read_text() != unit:
        FIREWALL_UNIT.write_text(unit)
        systemctl("daemon-reload")


def apply_rules() -> None:
    run([str(FIREWALL_SCRIPT)], check=True)
    systemctl("enable", "edgekit-firewall.service")


def rules_present(
    *, docker_subnet: str, wg_subnet: str, wg_if: str, docker_if: str = "docker0"
) -> bool:
    """Check the three rules the tunnel depends on, without modifying anything."""
    checks = (
        ["-t", "filter", "-C", "FORWARD", "-i", docker_if, "-o", wg_if, "-d", wg_subnet,
         "-j", "ACCEPT"],
        ["-t", "filter", "-C", "FORWARD", "-i", wg_if, "-o", docker_if, "-s", wg_subnet,
         "-m", "conntrack", "--ctstate", "ESTABLISHED,RELATED", "-j", "ACCEPT"],
        ["-t", "nat", "-C", "POSTROUTING", "-s", docker_subnet, "-d", wg_subnet,
         "-o", wg_if, "-j", "MASQUERADE"],
    )
    return all(run(["iptables", *check]).ok for check in checks)


def open_host_ports(*, wg_port: int, http_port: int, https_port: int) -> list[str]:
    """Open the guide §4 ports in ufw when ufw is the active firewall.

    Cloud-level firewalls (AWS security groups, Hetzner firewalls) are outside this host and
    cannot be opened from here — they are reported as a manual step by `edgekit doctor`.
    """
    if not has("ufw"):
        return []
    if "Status: active" not in run(["ufw", "status"]).stdout:
        return []

    opened = []
    for spec in (f"{wg_port}/udp", f"{http_port}/tcp", f"{https_port}/tcp"):
        if run(["ufw", "allow", spec]).ok:
            opened.append(spec)
    run(["ufw", "reload"])
    return opened


@dataclass(frozen=True)
class PortAdvice:
    protocol: str
    port: int
    purpose: str
    action: str  # "open" or "closed"


def cloud_firewall_ports(config: Config) -> list[PortAdvice]:
    """Every inbound port the operator must decide on at the cloud firewall.

    edgekit can open ufw on the host, but AWS security groups / Hetzner firewalls live
    outside the machine. This list is what setup prints after install.
    """
    return [
        PortAdvice("tcp", 22, "SSH (keep if you administer this server over SSH)", "open"),
        PortAdvice("udp", config.wireguard.listen_port, "WireGuard tunnel", "open"),
        PortAdvice("tcp", config.npm.http_port, "HTTP / ACME (Let's Encrypt)", "open"),
        PortAdvice("tcp", config.npm.https_port, "HTTPS", "open"),
        PortAdvice(
            "tcp",
            config.npm.admin_port,
            f"NPM admin UI (bound to {config.npm.admin_bind})",
            "closed",
        ),
        PortAdvice(
            "tcp",
            config.panel.port,
            f"edgekit panel (bound to {config.panel.bind})",
            "closed",
        ),
    ]


UFW_DEFAULTS = Path("/etc/default/ufw")
_UFW_RULE = re.compile(r"^(\d+)/(tcp|udp)\b", re.IGNORECASE)


@dataclass(frozen=True)
class PortCheck:
    protocol: str
    port: int
    purpose: str
    action: str
    allowed: bool | None
    ok: bool


@dataclass
class HostFirewallReport:
    installed: bool
    active: bool
    status_text: str
    ports: list[PortCheck]

    @property
    def ok(self) -> bool:
        if not self.installed or not self.active:
            return False
        return all(p.ok for p in self.ports)


def ensure_forward_policy_accept(path: Path | None = None) -> bool:
    """Docker → WireGuard forwarding needs ACCEPT; ufw's default DROP breaks it."""
    path = path or UFW_DEFAULTS
    if not path.exists():
        return False
    text = path.read_text()
    updated = text.replace('DEFAULT_FORWARD_POLICY="DROP"', 'DEFAULT_FORWARD_POLICY="ACCEPT"')
    updated = updated.replace("DEFAULT_FORWARD_POLICY='DROP'", "DEFAULT_FORWARD_POLICY='ACCEPT'")
    if updated == text:
        return False
    path.write_text(updated)
    return True


def enable_host_firewall(config: Config) -> HostFirewallReport:
    """Turn ufw on, allow the OPEN ports (SSH first), leave admin/panel closed."""
    if not has("ufw"):
        run(
            ["apt-get", "install", "-y", "--no-install-recommends", "ufw"],
            check=True,
        )
        if not has("ufw"):
            raise RuntimeError("ufw is not installed and apt-get could not provide it.")

    ensure_forward_policy_accept()
    run(["ufw", "default", "deny", "incoming"], check=True)
    run(["ufw", "default", "allow", "outgoing"], check=True)

    # SSH is first in cloud_firewall_ports so a failed enable cannot lock the operator out.
    for row in cloud_firewall_ports(config):
        if row.action != "open":
            continue
        run(["ufw", "allow", f"{row.port}/{row.protocol}"], check=True)

    run(["ufw", "--force", "enable"], check=True)
    run(["ufw", "reload"], check=False)
    return check_host_firewall(config)


def check_host_firewall(config: Config) -> HostFirewallReport:
    """Read ufw status and compare it to the OPEN / KEEP CLOSED list."""
    if not has("ufw"):
        return HostFirewallReport(installed=False, active=False, status_text="", ports=[])

    result = run(["ufw", "status"], check=False)
    status = result.stdout or result.stderr
    active = "Status: active" in status
    allowed = _allowed_specs(status) if active else set()

    ports: list[PortCheck] = []
    for row in cloud_firewall_ports(config):
        is_allowed = (row.protocol, row.port) in allowed if active else None
        if row.action == "open":
            ok = bool(is_allowed)
        else:
            ok = not bool(is_allowed)
        ports.append(
            PortCheck(row.protocol, row.port, row.purpose, row.action, is_allowed, ok)
        )
    return HostFirewallReport(installed=True, active=active, status_text=status, ports=ports)


def _allowed_specs(status: str) -> set[tuple[str, int]]:
    found: set[tuple[str, int]] = set()
    for line in status.splitlines():
        match = _UFW_RULE.match(line.strip())
        if not match or "ALLOW" not in line.upper():
            continue
        found.add((match.group(2).lower(), int(match.group(1))))
    return found
