"""Docker-to-WireGuard routing rules (guide §17) and host firewall openings (guide §4).

The guide's `iptables -A` commands are not idempotent and do not survive a reboot. Rather
than reach for iptables-persistent — which fights with Docker over the same tables — edgekit
writes a small idempotent script and a systemd unit that replays it after docker.service and
wg-quick@wg0 are up. Each rule is added only if an identical rule is absent (`iptables -C`),
so running the script any number of times converges on the same ruleset.
"""

from __future__ import annotations

import logging
import re
import stat
from dataclasses import dataclass
from pathlib import Path

from ..config import Config
from ..paths import FIREWALL_SCRIPT, FIREWALL_UNIT, SYSTEMD_DIR
from .shell import has, run, systemctl

log = logging.getLogger("edgekit.firewall")

SCRIPT_TEMPLATE = """#!/bin/sh
# Managed by edgekit. Regenerated by `edgekit provision`; edits are not preserved.
#
# Bridges the Docker bridge network to the WireGuard tunnel so that containers
# (Nginx Proxy Manager) can reach peers such as {wg_subnet}.
set -eu

DOCKER_IF="{docker_if}"
DOCKER_SUBNET="{docker_subnet}"
WG_IF="{wg_if}"
WG_SUBNET="{wg_subnet}"

# add <table> <chain> <rule...> — appends only when no identical rule exists.
add() {{
    table="$1"; shift
    chain="$1"; shift
    if ! iptables -t "$table" -C "$chain" "$@" 2>/dev/null; then
        iptables -t "$table" -A "$chain" "$@"
    fi
}}

# Container -> peer.
add filter FORWARD -i "$DOCKER_IF" -o "$WG_IF" -d "$WG_SUBNET" -j ACCEPT

# Peer -> container, replies only.
add filter FORWARD -i "$WG_IF" -o "$DOCKER_IF" -s "$WG_SUBNET" \\
    -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Peers see traffic as coming from the hub's tunnel address, so they need no route
# back to the Docker subnet.
add nat POSTROUTING -s "$DOCKER_SUBNET" -d "$WG_SUBNET" -o "$WG_IF" -j MASQUERADE
"""

UNIT_TEMPLATE = """[Unit]
Description=edgekit Docker-to-WireGuard forwarding rules
After=network-online.target ufw.service docker.service wg-quick@{wg_if}.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={script}

[Install]
WantedBy=multi-user.target
"""

DOCKER_AFTER_UFW_DROPIN = SYSTEMD_DIR / "docker.service.d" / "edgekit-after-ufw.conf"
DOCKER_AFTER_UFW_UNIT = "[Unit]\nAfter=ufw.service\n"


def detect_docker_bridge_subnet(default: str = "172.17.0.0/16") -> str:
    """Read the real bridge subnet instead of assuming 172.17.0.0/16 (guide §21)."""
    result = run(
        [
            "docker",
            "network",
            "inspect",
            "bridge",
            "--format",
            "{{(index .IPAM.Config 0).Subnet}}",
        ]
    )
    subnet = result.stdout.strip()
    if result.ok and "/" in subnet:
        return subnet
    log.warning("could not detect the Docker bridge subnet; falling back to %s", default)
    return default


def detect_docker_bridge_interface(default: str = "docker0") -> str:
    """Resolve the bridge's kernel interface name, which is configurable via daemon.json."""
    result = run(
        [
            "docker",
            "network",
            "inspect",
            "bridge",
            "--format",
            '{{index .Options "com.docker.network.bridge.name"}}',
        ]
    )
    name = result.stdout.strip()
    if result.ok and name and name != "<no value>":
        return name
    return default


@dataclass(frozen=True)
class DockerBridge:
    """A Docker bridge network as the kernel sees it: subnet plus interface name."""

    network: str
    subnet: str
    interface: str


_NETWORK_FORMAT = (
    "{{.Name}}|{{.Driver}}|"
    "{{if .IPAM.Config}}{{(index .IPAM.Config 0).Subnet}}{{end}}|"
    '{{index .Options "com.docker.network.bridge.name"}}|{{.Id}}'
)


def _inspect_bridge(network: str) -> DockerBridge | None:
    """Read one network, returning None unless it is a bridge with a usable subnet."""
    result = run(["docker", "network", "inspect", network, "--format", _NETWORK_FORMAT])
    if not result.ok:
        return None
    parts = [part.strip() for part in result.stdout.strip().split("|")]
    if len(parts) != 5:
        return None
    name, driver, subnet, interface, network_id = parts
    if driver != "bridge" or "/" not in subnet:
        return None
    if not interface or interface == "<no value>":
        # Compose networks carry no explicit name; the kernel calls them br-<id[:12]>.
        interface = "docker0" if name == "bridge" else f"br-{network_id[:12]}"
    return DockerBridge(network=name, subnet=subnet, interface=interface)


def container_bridges(container: str) -> list[DockerBridge]:
    """Every bridge network a container is really attached to.

    Compose gives Nginx Proxy Manager a project network of its own
    (``nginx-proxy-manager_default``) rather than the default ``bridge``, with its own
    subnet from the address pool and a ``br-<hash>`` interface. Rules written for
    docker0/172.17.0.0/16 therefore target an interface NPM holds no address on, and
    never match a single packet.
    """
    result = run(
        [
            "docker",
            "inspect",
            container,
            "--format",
            "{{range $name, $cfg := .NetworkSettings.Networks}}{{$name}}\n{{end}}",
        ]
    )
    if not result.ok:
        return []
    bridges = []
    for name in (line.strip() for line in result.stdout.splitlines()):
        if not name:
            continue
        bridge = _inspect_bridge(name)
        if bridge is not None:
            bridges.append(bridge)
    return bridges


def detect_proxy_bridge(config: Config) -> DockerBridge:
    """The bridge Nginx Proxy Manager sits on — the one the rules have to name."""
    bridges = container_bridges(config.npm.container_name)
    if bridges:
        return bridges[0]
    log.warning(
        "could not read %s's networks; falling back to the default bridge",
        config.npm.container_name,
    )
    return DockerBridge(
        network="bridge",
        subnet=detect_docker_bridge_subnet(config.server.docker_bridge_subnet),
        interface=detect_docker_bridge_interface(),
    )


def write_rules(
    *, docker_subnet: str, wg_subnet: str, wg_if: str, docker_if: str = "docker0"
) -> None:
    """Render the rules script and its boot-time unit."""
    script = SCRIPT_TEMPLATE.format(
        docker_if=docker_if,
        docker_subnet=docker_subnet,
        wg_if=wg_if,
        wg_subnet=wg_subnet,
    )
    FIREWALL_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    FIREWALL_SCRIPT.write_text(script)
    FIREWALL_SCRIPT.chmod(
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
    )

    unit = UNIT_TEMPLATE.format(wg_if=wg_if, script=FIREWALL_SCRIPT)
    unit_changed = not FIREWALL_UNIT.exists() or FIREWALL_UNIT.read_text() != unit
    if unit_changed:
        FIREWALL_UNIT.write_text(unit)
    dropin_changed = ensure_docker_starts_after_ufw()
    if unit_changed or dropin_changed:
        systemctl("daemon-reload")


def ensure_docker_starts_after_ufw() -> bool:
    """Docker must re-insert published-port NAT *after* ufw has rewritten iptables."""
    DOCKER_AFTER_UFW_DROPIN.parent.mkdir(parents=True, exist_ok=True)
    if (
        DOCKER_AFTER_UFW_DROPIN.exists()
        and DOCKER_AFTER_UFW_DROPIN.read_text() == DOCKER_AFTER_UFW_UNIT
    ):
        return False
    DOCKER_AFTER_UFW_DROPIN.write_text(DOCKER_AFTER_UFW_UNIT)
    return True


def restore_container_networking() -> None:
    """Re-insert Docker published ports and docker0↔wg0 rules after a ufw rewrite.

    ``ufw enable`` / ``ufw reload`` replace the kernel tables. ``ufw status`` can still
    show 80/443 ALLOW on INPUT while Docker's DNAT into Nginx Proxy Manager is gone,
    so Cloudflare times out on the origin until Docker is restarted.
    """
    run(["systemctl", "daemon-reload"], check=False)
    if has("docker"):
        run(["systemctl", "try-restart", "docker"], check=False)
    if FIREWALL_SCRIPT.is_file():
        run([str(FIREWALL_SCRIPT)], check=False)


def apply_rules() -> None:
    run([str(FIREWALL_SCRIPT)], check=True)
    systemctl("enable", "edgekit-firewall.service")


def _rules(
    *, docker_subnet: str, wg_subnet: str, wg_if: str, docker_if: str
) -> tuple[tuple[str, str, list[str]], ...]:
    """The script's three rules as ``(table, chain, match)`` — kept in step with SCRIPT_TEMPLATE."""
    return (
        ("filter", "FORWARD", ["-i", docker_if, "-o", wg_if, "-d", wg_subnet, "-j", "ACCEPT"]),
        ("filter", "FORWARD", ["-i", wg_if, "-o", docker_if, "-s", wg_subnet,
                               "-m", "conntrack", "--ctstate", "ESTABLISHED,RELATED",
                               "-j", "ACCEPT"]),
        ("nat", "POSTROUTING", ["-s", docker_subnet, "-d", wg_subnet, "-o", wg_if,
                                "-j", "MASQUERADE"]),
    )


def rules_present(
    *, docker_subnet: str, wg_subnet: str, wg_if: str, docker_if: str = "docker0"
) -> bool:
    """Check the three rules the tunnel depends on, without modifying anything."""
    rules = _rules(
        docker_subnet=docker_subnet, wg_subnet=wg_subnet, wg_if=wg_if, docker_if=docker_if
    )
    return all(
        run(["iptables", "-t", table, "-C", chain, *match]).ok for table, chain, match in rules
    )


def open_host_ports(*, wg_port: int, http_port: int, https_port: int) -> list[str]:
    """Open the guide §4 ports in ufw when ufw is the active firewall.

    Cloud-level firewalls (AWS security groups, Hetzner firewalls) are outside this host and
    cannot be opened from here — they are reported as a manual step by `edgekit doctor`.
    """
    if not has("ufw"):
        return []
    if "Status: active" not in run(["ufw", "status"]).stdout:
        return []

    opened = []
    for spec in (f"{wg_port}/udp", f"{http_port}/tcp", f"{https_port}/tcp"):
        if run(["ufw", "allow", spec]).ok:
            opened.append(spec)
    run(["ufw", "reload"])
    restore_container_networking()
    return opened


def allow_docker_to_panel(config: Config) -> list[str]:
    """Let the NPM container reach the panel on the hub IP.

    10.50.0.1 is a local address, so that packet is INPUT, not FORWARD. ufw's
    default deny drops it, NPM waits on the backend, and HTTPS on :443 hangs
    even though 443/tcp is allowed. The panel stays closed from the internet.

    The source has to be the subnet NPM is really on. Compose gives it a project
    network of its own, so allowing the default bridge opens a path nothing uses and
    leaves ``edgekit.<zone>`` timing out with 80/443 apparently fine.
    """
    if not has("ufw"):
        return []
    bind = (config.panel.bind or "").strip()
    if not bind or bind in ("127.0.0.1", "localhost", "::1"):
        return []

    subnets = [bridge.subnet for bridge in container_bridges(config.npm.container_name)]
    if not subnets:
        subnets = [config.server.docker_bridge_subnet or "172.17.0.0/16"]

    for subnet in subnets:
        run(
            [
                "ufw",
                "allow",
                "from",
                subnet,
                "to",
                bind,
                "port",
                str(config.panel.port),
                "proto",
                "tcp",
            ],
            check=True,
        )
    _revoke_stale_panel_rules(config, keep=subnets)
    return subnets


def _revoke_stale_panel_rules(config: Config, *, keep: list[str]) -> None:
    """Drop panel openings for bridges NPM is not on.

    Earlier releases allowed the default bridge, which NPM was never attached to. Left
    in place it hands the panel to every unrelated container on docker0.
    """
    bind = (config.panel.bind or "").strip()
    status = run(["ufw", "status"], check=False).stdout
    for subnet in _panel_rule_sources(status, bind, config.panel.port):
        if subnet in keep:
            continue
        run(
            [
                "ufw",
                "delete",
                "allow",
                "from",
                subnet,
                "to",
                bind,
                "port",
                str(config.panel.port),
                "proto",
                "tcp",
            ],
            check=False,
        )


def _panel_rule_sources(status: str, bind: str, port: int) -> list[str]:
    """Source subnets of existing `<bind> <port>/tcp ALLOW <subnet>` rules."""
    target = f"{bind} {port}/tcp"
    sources = []
    for line in status.splitlines():
        line = line.strip()
        if not line.startswith(target) or "ALLOW" not in line.upper():
            continue
        source = line.split()[-1]
        if "/" in source:
            sources.append(source)
    return sources


def remove_edgekit_rules(config: Config) -> list[str]:
    """Undo write_rules, apply_rules, open_host_ports and allow_docker_to_panel.

    ufw itself, its SSH rule and its forward policy stay: taking those away can lock the
    operator out of the server they are cleaning up.
    """
    removed: list[str] = []
    wg_if, wg_subnet = config.wireguard.interface, config.wireguard.subnet

    if has("iptables"):
        bridge = detect_proxy_bridge(config)
        rules = _rules(
            docker_subnet=bridge.subnet, wg_subnet=wg_subnet, wg_if=wg_if,
            docker_if=bridge.interface,
        )
        deleted = 0
        for table, chain, match in rules:
            # The script appends only when absent, but earlier releases could duplicate.
            while run(["iptables", "-t", table, "-C", chain, *match]).ok:
                if not run(["iptables", "-t", table, "-D", chain, *match]).ok:
                    break
                deleted += 1
        if deleted:
            removed.append(f"{deleted} iptables rule(s)")

    if FIREWALL_UNIT.exists():
        systemctl("disable", "--now", "edgekit-firewall.service")
    for path in (FIREWALL_UNIT, FIREWALL_SCRIPT, DOCKER_AFTER_UFW_DROPIN):
        if path.exists():
            path.unlink()
            removed.append(str(path))
            try:
                path.parent.rmdir()  # only when nothing else lives there
            except OSError:
                pass
    if removed:
        systemctl("daemon-reload")

    if has("ufw") and "Status: active" in run(["ufw", "status"]).stdout:
        bind, port = (config.panel.bind or "").strip(), config.panel.port
        for subnet in _panel_rule_sources(run(["ufw", "status"]).stdout, bind, port):
            run(["ufw", "delete", "allow", "from", subnet, "to", bind, "port", str(port),
                 "proto", "tcp"])
        for spec in (
            f"{config.wireguard.listen_port}/udp",
            f"{config.npm.http_port}/tcp",
            f"{config.npm.https_port}/tcp",
        ):
            run(["ufw", "delete", "allow", spec])
        run(["ufw", "reload"])
        # ufw reload drops Docker's own NAT rules; other containers need them back.
        restore_container_networking()
        removed.append("ufw rules for WireGuard, HTTP, HTTPS and the panel")
    return removed


@dataclass(frozen=True)
class PortAdvice:
    protocol: str
    port: int
    purpose: str
    action: str  # "open" or "closed"


def cloud_firewall_ports(config: Config) -> list[PortAdvice]:
    """Every inbound port the operator must decide on at the cloud firewall.

    edgekit can open ufw on the host, but AWS security groups / Hetzner firewalls live
    outside the machine. This list is what setup prints after install.
    """
    return [
        PortAdvice("tcp", 22, "SSH (keep if you administer this server over SSH)", "open"),
        PortAdvice("udp", config.wireguard.listen_port, "WireGuard tunnel", "open"),
        PortAdvice("tcp", config.npm.http_port, "HTTP / ACME (Let's Encrypt)", "open"),
        PortAdvice("tcp", config.npm.https_port, "HTTPS", "open"),
        PortAdvice(
            "tcp",
            config.npm.admin_port,
            f"NPM admin UI (bound to {config.npm.admin_bind})",
            "closed",
        ),
        PortAdvice(
            "tcp",
            config.panel.port,
            f"edgekit panel (bound to {config.panel.bind})",
            "closed",
        ),
    ]


UFW_DEFAULTS = Path("/etc/default/ufw")
_UFW_RULE = re.compile(r"^(\d+)/(tcp|udp)\b", re.IGNORECASE)


@dataclass(frozen=True)
class PortCheck:
    protocol: str
    port: int
    purpose: str
    action: str
    allowed: bool | None
    ok: bool


@dataclass
class HostFirewallReport:
    installed: bool
    active: bool
    status_text: str
    ports: list[PortCheck]

    @property
    def ok(self) -> bool:
        if not self.installed or not self.active:
            return False
        return all(p.ok for p in self.ports)


def ensure_forward_policy_accept(path: Path | None = None) -> bool:
    """Docker → WireGuard forwarding needs ACCEPT; ufw's default DROP breaks it."""
    path = path or UFW_DEFAULTS
    if not path.exists():
        return False
    text = path.read_text()
    updated = text.replace('DEFAULT_FORWARD_POLICY="DROP"', 'DEFAULT_FORWARD_POLICY="ACCEPT"')
    updated = updated.replace("DEFAULT_FORWARD_POLICY='DROP'", "DEFAULT_FORWARD_POLICY='ACCEPT'")
    if updated == text:
        return False
    path.write_text(updated)
    return True


def enable_host_firewall(config: Config) -> HostFirewallReport:
    """Turn ufw on, allow the OPEN ports (SSH first), leave admin/panel closed."""
    if not has("ufw"):
        run(
            ["apt-get", "install", "-y", "--no-install-recommends", "ufw"],
            check=True,
        )
        if not has("ufw"):
            raise RuntimeError("ufw is not installed and apt-get could not provide it.")

    ensure_forward_policy_accept()
    run(["ufw", "default", "deny", "incoming"], check=True)
    run(["ufw", "default", "allow", "outgoing"], check=True)

    # SSH is first in cloud_firewall_ports so a failed enable cannot lock the operator out.
    for row in cloud_firewall_ports(config):
        if row.action != "open":
            continue
        run(["ufw", "allow", f"{row.port}/{row.protocol}"], check=True)
    allow_docker_to_panel(config)

    run(["ufw", "--force", "enable"], check=True)
    run(["ufw", "reload"], check=False)
    ensure_docker_starts_after_ufw()
    restore_container_networking()
    return check_host_firewall(config)


def check_host_firewall(config: Config) -> HostFirewallReport:
    """Read ufw status and compare it to the OPEN / KEEP CLOSED list."""
    if not has("ufw"):
        return HostFirewallReport(installed=False, active=False, status_text="", ports=[])

    result = run(["ufw", "status"], check=False)
    status = result.stdout or result.stderr
    active = "Status: active" in status
    allowed = _allowed_specs(status) if active else set()

    ports: list[PortCheck] = []
    for row in cloud_firewall_ports(config):
        is_allowed = (row.protocol, row.port) in allowed if active else None
        if row.action == "open":
            ok = bool(is_allowed)
        else:
            ok = not bool(is_allowed)
        ports.append(
            PortCheck(row.protocol, row.port, row.purpose, row.action, is_allowed, ok)
        )
    return HostFirewallReport(installed=True, active=active, status_text=status, ports=ports)


def _allowed_specs(status: str) -> set[tuple[str, int]]:
    """Ports allowed from Anywhere. Source-restricted rules (Docker → panel) are not public."""
    found: set[tuple[str, int]] = set()
    for line in status.splitlines():
        match = _UFW_RULE.match(line.strip())
        if not match or "ALLOW" not in line.upper():
            continue
        if "ANYWHERE" not in line.upper():
            continue
        found.add((match.group(2).lower(), int(match.group(1))))
    return found
